bookkeeper: fix page count race condition
java.lang.IllegalStateException: Use count has gone below 0
at org.apache.bookkeeper.bookie.LedgerEntryPage.releasePage(LedgerEntryPage.java:86)
at org.apache.bookkeeper.bookie.IndexInMemPageMgr.grabLedgerEntryPage(IndexInMemPageMgr.java:406)
at org.apache.bookkeeper.bookie.IndexInMemPageMgr.getEntryOffset(IndexInMemPageMgr.java:526)
at org.apache.bookkeeper.bookie.LedgerCacheImpl.getEntryOffset(LedgerCacheImpl.java:74)

we didn't reset the lep to null for some if conditional branches. so if lruCleanPageMap.size becomes equal to or less than 0, the lep will be returned by mistake and without calling #usePage. And this page will be released of the caller, so the page count decreased to less than 0. this was found when I prepared the patch for https://issues.apache.org/jira/browse/BOOKKEEPER-659.

the fix is to
- ensure lep is setting to null after one grab iteration is finished.
- remove redundant lep == null checking to address findbugs error.

RB_ID=207980